### ISSUE TITLE
[I] Repeated requests to paste security token when creating note from web page

### ISSUE THREAD

**Issue by pbek** [qownnotes/web-companion#10]
moved from https://github.com/pbek/QOwnNotes/issues/1211 by @truthsword

**Comment by pbek** [comment]
## 19.5.5
- the **security token** will now be sent correctly to QOwnNotes for context menu operations

There now is a new release in the stores, could you please test it and report if it works for you, @truthsword?

**Comment by truthsword** [comment]
That worked. I tried several "create note" combinations (html, screenshot, text selection) and each was captured. Changed security token to my own creation, and capture continued to work. 

I tested using Win10x64-1809 and Edge Chromium (Dev) browser with Chrome store extension.

**Comment by pbek** [comment]
Great, thank you for reporting and testing!
