### ISSUE TITLE
Web-companion only finds bookmarks when in QOwnNote the note Bookmarks is selected

### ISSUE THREAD

**Issue by avalx** [qownnotes/web-companion#11]
DELETED: I found out in the documentation this is by design. Sorry for false alarm!

**Comment by pbek** [comment]
You have to tag the notes with a `bookmarks` tag in QOwnNotes. :wink: (see QOwnNotes settings)

**Comment by avalx** [comment]
OK now I got it, thanks!

**Comment by pbek** [comment]
see: https://www.qownnotes.org/Knowledge-base/QOwnNotes-Web-Companion-browser-extension
