### ISSUE TITLE
Enable Edge (chromium) extension to copy from Edge's "Immersive reader"

### ISSUE THREAD

**Issue by truthsword** [qownnotes/web-companion#13]
#### Expected behaviour

Right-click, Create note from page using web-companion, copies formatted text to QON.

#### Actual behaviour

Doesn't work... Warning pop-up appears 
![](https://i.imgur.com/25jj3kZ.png)

I'm using the new chromium-based Edge..
_**Microsoft Edge is up to date.
Version 79.0.308.1 (Official build) dev (64-bit)**_

#### Steps to reproduce

Open web page, Select "Enter Immersive Reader..." icon.
When page loads, right-click text and attempt to "Create note from page"

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Oct 28 19:31:00 2019`
**Version**: `19.10.11`
**Build date**: `Oct 28 2019`
**Build number**: `4699`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.0`
**Qt Version (runtime)**: `5.13.0`
**Portable mode**: `no`
</details>

FWIW, it fails too with Firefox web-companion extension in Reader mode.

**Comment by pbek** [comment]
Note: moved from https://github.com/pbek/QOwnNotes/issues/1334

**Comment by pbek** [comment]
I haven't found a permission to use to allow accessing `read://` urls (https://developer.chrome.com/extensions/tabs). Have you found anything about that topic?

**Comment by truthsword** [comment]
Nothing here. I tried alternate clipping software and they too failed.

**Comment by pbek** [comment]
Too bad. Let me know if you find something.
