### ISSUE TITLE
"Create note from selection" URL reference.

### ISSUE THREAD

**Issue by truthsword** [qownnotes/web-companion#14]
When selecting browser text and using the extension's "Create note from selection" feature, would it be possible to append the source URL to the captured text? 

Often I've copied a snippet of text, only later wanting to revisit the URL for additional context/clarification/links/etc.

**Comment by pbek** [comment]
But it does for me:

![image](https://user-images.githubusercontent.com/1798101/68072729-f2a83400-fd88-11e9-9950-904bdbc23632.png)

**Comment by truthsword** [comment]
Apologies. How did I not see that. Please delete this thread.

... but, before you do, please tell me how to prevent the training "=============..."
I get on every copy (even screenshots).
![](https://i.imgur.com/hgRasPf.png)

**Comment by pbek** [comment]
That's strange, I don't get that... Do you get that on every page? Maybe open another issue.

**Comment by pbek** [comment]
> Maybe open another issue.

The issue should please be made on the QOwnNotes issue tracker.

**Comment by truthsword** [comment]
It's apparently a "settings" issue... So I have some sleuthing to do.

**Comment by pbek** [comment]
I'm curious what is was when you track it down... :smile_cat:

**Comment by truthsword** [comment]
I found it... and it is a strange puppy. It is a font issue... For example...

With these settings all is fine (no trailing ======)
![](https://i.imgur.com/4jMDaQP.png)

But if I increase the MS Shell Dlg font...say to 12
![](https://i.imgur.com/ktMQBj6.png)

then I get this...
![](https://i.imgur.com/fBnG6bU.png)

Bringing the font back to "8" "fixes" things... except for my eyesight 😣

I discovered this with a new profile, and when I went back to my profile and reset the font to "8", the trailing ===== no longer occurred.

Hopefully, you can reproduce/fix 😉 Thanks!
