### ISSUE TITLE
[F] Copy Selected Text from Nextcloud PDF Viewer (Firefox Web Extension)

### ISSUE THREAD

**Issue by nater85** [qownnotes/web-companion#15]
#### Expected behaviour

When using Evernote web clipper the selected text is exported into the note as desired, which suggests it is possible to extract the text from the PDF viewer pane in Nextcloud.

When opening the PDF in Firefox (not within Nextcloud PDF viewer), the selected text is added to the note as expected (along with the web address to the PDF).

#### Actual behaviour

With the QOwnNotes Firefox Web Extension, the note contains only the web address:

 '<Server IP>&fileid=3435#pdfviewer'
 
 and not the selected text from the PDF document.

#### Steps to reproduce

1. Open a PDF in Nextcloud.
2. Select Text by dragging mouse
3. Right Click and Select 'Create note from selection'

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[12:52:02] [status] Stored current note to disk
[12:52:05] [status] Notes directory was modified externally
[12:52:05] [status] Stored 1 note(s) to disk
[12:52:07] [status] Notes directory was modified externally
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Thu Nov 14 12:36:30 2019`
**Version**: `19.11.13`
**Build date**: `Nov 14 2019`
**Build number**: `618`
**Platform**: `linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.12.2`
**Qt Version (runtime)**: `5.12.2`
**Portable mode**: `no`
**Settings path / key**: `/home/USER/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/USER/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application dictionaries path**: `/home/USER/.local/share/PBE/QOwnNotes/dicts`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `Adwaita`
**Notes in current note folder**: `10`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-11-14T12:13:31.452`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Sans Serif,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans Serif,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `true`
**appMetrics/disableTracking** (bool): `true`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `15`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `false`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**restoreCursorPosition** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `2TEXQK9R - Files - Nextcloud 2019-11-14T12.32.31`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `uDstqppC`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**LANGUAGE**: `en_US:en`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SHLVL**: `0`
**QT4_IM_MODULE**: `xim`
**GTK_MODULES**: `gail:atk-bridge`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `2`
**WINDOWPATH**: `2`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DISPLAY**: `:1`
**LANG**: `en_US.UTF-8`
**XMODIFIERS**: `@im=ibus`
**XAUTHORITY**: `/run/user/1000/gdm/Xauthority`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `pop`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**QT_IM_MODULE**: `ibus`
**XDG_VTNR**: `2`
**CLUTTER_IM_MODULE**: `xim`
**XDG_DATA_DIRS**: `/usr/share/pop:/usr/local/share/:/usr/share/`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**XDG_MENU_PREFIX**: `gnome-`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `20136`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
</details>

**Comment by pbek** [comment]
You could script the web scraper yourself now and see what's happening with the html you get, see #16 and #17.
