### ISSUE TITLE
Notes from the same web page

### ISSUE THREAD

**Issue by ZiluTian** [qownnotes/web-companion#16]
Hello, 

Thank you for this tool! I am writing to see if it is possible to merge notes from the same web page to the same note in QOwnnotes, rather than one note per entry. Is there any suggestion is how to do this efficiently? Thanks! 

Regards, 
Zilu

**Comment by pbek** [comment]
Thank you for your kind words. 

> if it is possible to merge notes from the same web page to the same note in QOwnnotes, rather than one note per entry

Do you mean `Create note from selection`?
No, currently always a new note is created.

**Comment by ZiluTian** [comment]
Hello,

Thanks for your prompt reply!

Ok, too bad. I will try to get the merge note script to work then.


Regards,
Zilu

**Comment by pbek** [comment]
You will be able to write your own script to handle it the way you like.

## 20.5.0
- the context menu entries `Create note from page (HTML import)` and `Create note from selection`
  where renamed to `Send page to QOwnNotes` and `Send selection to QOwnNotes`, because now a screenshot of the current page will also be sent to QOwnNotes so you are able to use them in scripts
    - you need QOwnNotes 20.5.7 or higher for this feature
    - the default behavior is still that a new note is created with the page or selection text

**Comment by pbek** [comment]
## QOwnNotes 20.5.7
- there now is a new method `insertHtmlAsMarkdownIntoCurrentNote` for `mainWindow`
  in the scripting engine that inserts html in the current note as markdown
  (for [#1740](https://github.com/pbek/QOwnNotes/issues/1740))
    - this method also downloads remote images and transforms `data:image` urls
      to local images stored in the media directory
    - for more information please take a look at the
      [Mainwindow scripting documentation](https://docs.qownnotes.org/en/latest/scripting/classes/#mainwindow)
- added a new scripting hook `websocketRawDataHook` that is called when data is
  sent from the QOwnNotes Web Companion browser extension via the web browser's
  context menu (for [#1740](https://github.com/pbek/QOwnNotes/issues/1740))
    - you need the QOwnNotes Web Companion 20.5.0 or higher for this to work
    - this works with either the `send page` and `send selection` feature of the
      web companion
    - if a hook implementation is found in a script no new note will be created
    - take a look at the
      [handleNoteNameHook documentation](https://docs.qownnotes.org/en/latest/scripting/hooks/#websocketrawdatahook)
      for more information

There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
Don't forget to update the QOwnNotes browser extension!
