### ISSUE TITLE
[Feature request] Capture images

### ISSUE THREAD

**Issue by barolo** [qownnotes/web-companion#23]
Usually I clip whole pages churned out by some kind of readability parser, making them easy to digest, Is there a reason as to why companion omits images? 
Sometimes it seems to capture them by mistake when link is something like "....max/60/1*wXR3F3VWzAKzL9c6FMqVbQ.png?q=20"

Edit. Weirdly enough it captures them when they're inlined as data [ <img src="data:image... ]
One of my rss readers exports like that, so that's a workaround

**Comment by pbek** [comment]
Well, it depends if the images are accessible in the html... Or even readable outside the webpage. 

You can use this scripting hook (https://docs.qownnotes.org/en/latest/scripting/hooks/#websocketrawdatahook) to write a script to see how the html looks like you get from the browser. Maybe you can correct the html you get if it's to mangled by the browser or webpage.

**Comment by barolo** [comment]
Tested it with more sites and it actually gets the images, guess you're right and it's site dependent
