### ISSUE TITLE
Setting for Sending selected text to Currently Active Note

### ISSUE THREAD

**Issue by v3ss0n** [qownnotes/web-companion#26]
#### Expected behaviour
When selected text is sent , it should go to current note instead of making new note .
There should be a setting to allow that.
#### Actual behaviour
When slected text is sent - it makes a new note , only goes if selected text of same link is sent again

#### Steps to reproduce
- RIght Click selected text
- Send to QOwnNotes

**Comment by pbek** [comment]
You can do that already with the help of the scripting engine: https://www.qownnotes.org/scripting/hooks.html#websocketrawdatahook

There also is an example linked there that does exactly that.

**Comment by v3ss0n** [comment]
Thank you very much , i am checking now. 
I am loving QOwnNotes , it is best i had tried  ( Tried  Evernote , Joplin , Zettlr , all other electron based markdown notes) .
QOwnNotes is what i am looking for past 5-6 years since Basket become unmaintained.

**Comment by pbek** [comment]
Thank you! 😁  I was on Basket too, but I didn't like the lock-in into a file format and I wanted to use my notes on all platforms and sync them around. 😀

**Comment by v3ss0n** [comment]
Nitce to know main developer was basket user too. Basket is ancient now since no development for so long. QOwnNotes is far  flexible and i really love no lock-in file format. Wheni startted  I export my notes from Joplin as Markdown with subfolders and then i point that forlder  in QownNotes -  and it works like magic. 
Only thing missing from QownNotes is basket style note organization - columns of  notes and easily sorting and grouping them , what do you think? fit in QOwnNotes scope?

**Comment by pbek** [comment]
> - columns of notes and easily sorting and grouping them , what do you think? fit in QOwnNotes scope?

Since QON doesn't have the notes in a database (like basket) this is hard to achieve, the only source of truth is the folder structure of your note folder...

**Comment by v3ss0n** [comment]
Could be done as  extra folder list view with columns of notes for as an optional setting. 
Sorting will be only Alphabetical or by Modified.

That way if user choose to enable coulmn mode of small text files , he can.
Grouping will be folder/Subfolder structure.

Doable but could be a lot of work.

**Comment by pbek** [comment]
A huge amount of work and it would introduce a lot of regressions for sure.

**Comment by v3ss0n** [comment]
I agree , not proper way to do too. Better keep this way,
