### ISSUE TITLE
Connection Error when trying to use extension in any way

### ISSUE THREAD

**Issue by funkotron** [qownnotes/web-companion#3]
Error message:
```
Connection to QOwnNotes failed!
undefined
```

Version:
```
2019.1.7
Updated January 21, 2019
```

**Comment by pbek** [comment]
Can you please post the output from the debug settings of QOwnNotes? Which version of QOwnNotes are you using? Did you start it?

**Comment by pbek** [comment]
I will close this issue until there is more information.
