### ISSUE TITLE
The Librewolf (Firefox add) will not connect to QownNotes app

### ISSUE THREAD

**Issue by coffseducation** [qownnotes/web-companion#39]
QownNotes addon is added to Librewolf and the code is pasted from the QownNotes desktop app.

Librewolf does not permit the connection -??

Error displayed:

Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:1
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:19885
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:1
[Exception... "Conduits:RuntimeMessage: message reply cannot be cloned."  nsresult: "0x80004005 (DataCloneError)"  location: "<unknown>"  data: no] ConduitsParent.jsm:362
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:1
[Exception... "Conduits:RuntimeMessage: message reply cannot be cloned."  nsresult: "0x80004005 (DataCloneError)"  location: "<unknown>"  data: no] 6 ConduitsParent.jsm:362
[Exception... "Conduits:RuntimeMessage: message reply cannot be cloned."  nsresult: "0x80004005 (DataCloneError)"  location: "<unknown>"  data: no] 3 ConduitsParent.jsm:362
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:1
[Exception... "Conduits:RuntimeMessage: message reply cannot be cloned."  nsresult: "0x80004005 (DataCloneError)"  location: "<unknown>"  data: no] ConduitsParent.jsm:362
[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 73"  data: no] 3 ExtensionCommon.jsm:73:12
[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 73"  data: no] ExtensionCommon.jsm:73:12
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:1
[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 73"  data: no] ExtensionCommon.jsm:73:12
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:1
ExtensionError: No such native application fx_cast_bridge ExtensionUtils.jsm:58:5
Error: fx_cast (Error): Bridge connection failed and backup not enabled. background.js:1:1304
Request for font "Cousine" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Mono" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Naskh Arabic" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Thai" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Devanagari" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Tamil" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Bengali" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Telugu" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Kannada" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Malayalam" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Gurmukhi" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Gujarati" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Oriya" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Armenian" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Georgian" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Ethiopic" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Myanmar" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Sinhala" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Coptic" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Deseret" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Tai Tham" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Cherokee" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Chakma" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Osage" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Symbols" blocked at visibility level 1 (requires 3)
index.html
Request for font "Noto Sans Symbols2" blocked at visibility level 1 (requires 3)
index.html
NetworkError: Network request failed Utils.jsm:132
NetworkError: Network request failed 2 Utils.jsm:132
NetworkError: Network request failed Utils.jsm:132
BroadcastService: receivedBroadcastMessage: handler for remote-settings/monitor_changes threw error: Error: Polling for changes failed: NetworkError: Network request failed.
    pollChanges resource://services-settings/remote-settings.js:254
PushBroadcastService.jsm:264
ExtensionError: No such native application fx_cast_bridge ExtensionUtils.jsm:58:5
Error: fx_cast (Error): Bridge connection failed and backup not enabled. background.js:1:1304

#### Expected behaviour

Highlighted text gets saved as a note in QownNotes when right clicking the 'Send to QOwnNotes' addon.

Librewolf 97.0.1 Appimage

Operating System: Kubuntu 21.10
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-35-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630

**Comment by pbek** [comment]
I've no idea how Librewolf is handling things differently than Firefox...

Two things that come to mind:

- Is QOwnNotes running and the socket server (in the Browser extension settings) enabled?
  - Are there any logs in the logging panel of QOwnNotes with Debug logs turned on?
- What happens if you click the QOwnNotes icon in the extensions toolbar?

**Comment by coffseducation** [comment]
This seems to have been the problem!
> 
> 
> * What happens if you click the QOwnNotes icon in the extensions toolbar of your Browser?

User data consent

This is a companion extension for QOwnNotes to interact with the note taking desktop application.

This browser extension collects personal user data to send it to your local instance of QOwnNotes via a WebSocket. The data collected may include the following information:

    Information about your browser tabs, like the URL, to store bookmarks in QOwnNotes
    The content of your open tab, if you want to send it to QOwnNotes as a note
    A screenshot of your open tab, if you want to send it to QOwnNotes as a note
    Your browser bookmarks, if you want to import them into QOwnNotes

This extension doesn't work without communicating to your local instance of QOwnNotes and sending user data back and forth. No user data is sent over the internet or to any other party! 

After accepting the addon works!

Thanks Pat - and sorry for wasting your time with my trivial user error!

Much appreciated!

**Comment by pbek** [comment]
No problem. 😉  Mozilla is requiring extensions to ask users for this kind of consent if the extension is accessing a browser tab.
