### ISSUE TITLE
Keyboard Shortcuts in Firefox

### ISSUE THREAD

**Issue by tosigus** [qownnotes/web-companion#4]
#### Expected behaviour
Press Ctrl+B, open Web Companion open Pop-Up.

#### Actual behaviour
Firefox opens Firefox Bookmarks.

#### Steps to reproduce
Press Ctrl+B (Windows 10 and Ubuntu 18.04).

**Comment by pbek** [comment]
This is kind of hard-coded in Firefox. In Firefox 66 and newer (currently Firefox Nightly) you can at least set a shortcut in the settings for extensions. I use `Alt+Shift+B` by default.

Does this answer your question?

**Comment by tosigus** [comment]
Yes, it does! Could you change the README.md?

**Comment by pbek** [comment]
If you want you also change the text to your liking. (just click the edit button) I'm open for a pull request. :)

**Comment by tosigus** [comment]
Thanks, done.
