### ISSUE TITLE
Can't trigger extension using keyboard shortcut in Firefox

### ISSUE THREAD

**Issue by husimo-tilleuls** [qownnotes/web-companion#48]
#### Expected behaviour

Would like to be able to use the QOwnNotes web companion using keyboard shortcut `Ctrl + Shift + B` 

#### Actual behaviour

It triggers the bookmarks bar (displays and hides).

#### Steps to reproduce

Maybe it's related to a French Firefox version, i dunno.

#### Output from the debug section in the settings dialog in QOwnNotes

Don't think it's relevant here but can send it if necessary

#### Relevant log output in the Log panel in QOwnNotes

Don't think it's relevant here but can send it if necessary

**Comment by pbek** [comment]
I guess (your?) Firefox doesn't honor the default shortcut set here:

https://github.com/qownnotes/web-companion/blob/a5992472fdaac4fd455fe7789def956a19ff1cb2/app/manifest.json#L68-L72

**Comment by pbek** [comment]
I personally use `Ctrl+Alt+B` everywhere. Maybe I just set that as default too now...

**Comment by pbek** [comment]
What "other shortcuts like Chrome"?

**Comment by husimo-tilleuls** [comment]
Okay, nice. I tried it the first one : https://github.com/qownnotes/web-companion/blob/develop/README.md?plain=1#L57

And Firefox triggers the menu bar on Alt key ;'(

**Comment by pbek** [comment]
> I personally use Ctrl+Alt+B everywhere.

You can set that shortcut too in the Firefox extension settings, those are well hidden in Firefox. 😬 

![image](https://user-images.githubusercontent.com/1798101/208690491-55c7427a-c240-4517-a3d8-749c67e92d09.png)

**Comment by pbek** [comment]
> And Firefox triggers the menu bar on Alt key ;'(

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey says `Alt + Shift`.

**Comment by husimo-tilleuls** [comment]
Nice, it's working, thank you!

**Comment by pbek** [comment]
## 22.12.0
- changed Firefox default shortcut to <kbd>Ctrl + Alt + B</kbd> since the browser blocked <kbd>Ctrl + Shift + B</kbd>
  (for [#48](https://github.com/qownnotes/web-companion/issues/48))

There now is a new release, could you please test it and report if it works for you?

**Comment by husimo-tilleuls** [comment]
Hello, thank you! It's not yet available in my Firefox and I don't have time right now to install it manually but I'll tell you ASAP ;-)

**Comment by pbek** [comment]
Mozilla neems some time for the review process...

**Comment by husimo-tilleuls** [comment]
LGTM! Thank's a lot!

If there's any way to support your work I would be glad to!

**Comment by pbek** [comment]
Thank you. :) Reporting issues that creep up when browser vendors change things already helps a lot.
