### ISSUE TITLE
[BUG] some web clipper images are saved without an extension

### ISSUE THREAD

**Issue by azurew4r3** [qownnotes/web-companion#51]
Platform: Windows 10
Browser: Vivaldi

#### Expected behaviour
linked images saved with valid filename and extension (ie: filename.png or filename.svg)
#### Actual behaviour
notes saved via chrome's web extension "Create note with screenshot of visible page" appends the image file name with a dot (without an extension)
```
 example:
 ![media-AtKGem](media/media-AtKGem.)
```
when viewing the "Manage stored images" panel, the image file name is displayed without the dot  (and without an extension)
```
 example:
 media-AtKGem
```
with that difference, these images are listed as "orphaned"

Further testing to pinpoint issue:

Saving a page via chrome's web extension option "Send page .." does name images with a proper extension. As does insert image from the Edit menu.

these images are not listed as "orphaned"

#### Steps to reproduce
with "QOwnNotes Companion Browser Extension" installed

right click a web page
select "Create note with screenshot of visible page"
view the new note's image link within the Edit panel

**Comment by pbek** [comment]
I guess you are talking about a feature of qownnotes, can you please open an issue there?

**Comment by azurew4r3** [comment]
I had started to post this as a QOwnNotes bug report. Then noticed this only happens with  images from the web clipper. And more specifically, from the "Create note with screenshot .." option. So I aborted that report, and posted it here.

I could have worded the title better, can I edit that? It turns out I can! Please advise if this should still be moved, reposted over yonder.

**Comment by pbek** [comment]
After I deleted the note, the image was "orphaned" properly...

**Comment by azurew4r3** [comment]
Ok will do, I will close this and re-post as QOwnNotes issue.
