### ISSUE TITLE
Stick web companion application to one specific note in QOwnNotes

### ISSUE THREAD

**Issue by Airgunster** [qownnotes/web-companion#6]
_This is not a bug report, but a feature related item_

Hi there,

Do you think it will be a great idea to be able to _stick_ web companion application in the browser to one specific note in QOwnNotes? Current behavior is that it always be showing (and saving) bookmarks into random notes you have already selected in your QOwnNotes, and new behavior will allow you to store your bookmarks correctly in one single place.

What do you think?

Thanks again for wonderful software!
Alexey

**Comment by pbek** [comment]
> Thanks again for wonderful software!

Thank you for your kind words!

> new behavior will allow you to store your bookmarks correctly in one single place.

the current behavior is that all new bookmarks will be stored in **one** note you defined (`Bookmarks` by default), I think I don't understand what your wish is.

**Comment by pbek** [comment]
I will close this issue until there is more information.
