### ISSUE TITLE
Creating a new note from the current selection enhanced

### ISSUE THREAD

**Issue by ianzhuo** [qownnotes/web-companion#7]
Hi,

In QOwnNotes, we can use ctrl+shift+v to paste html and images.
Is it possible to make `creating a new note from selection` behave like `paste html`.
I thought it will be very helpful when doing a quick web clip.

Thanks.

**Comment by pbek** [comment]
> Is it possible to make creating a new note from selection behave like paste html.

Can you please explain in more detail what you are expecting.

**Comment by ianzhuo** [comment]
>Features:
>...
>    creating a new note (only text) from the current selection by right-clicking it

If I want to clip part of html by using web companion, it only creates a new text-only note in QOwnNotes for now.
Is it possibile making current selection to create a new note and converted it to markdown and download images, just like QOwnNotes shortcut `Ctrl+Alt+V` did.

>creating a new note from the content of the current webpage by right-clicking on the page

Besides, directly convert entire web page to markdown maybe is not a good idea, most of web pages contain lot's of clutters.
I would suggest to declutter web page before clipping.

FYI, I also using [Quiver Web Clipper](https://addons.mozilla.org/zh-TW/firefox/addon/quiver-web-clipper/) as a clutter free reader and md converter.

Please excuse my poor English, and hope my explanation is clear enough.

**Comment by pbek** [comment]
> Is it possibile making current selection to create a new note and converted it to markdown and download images, just like QOwnNotes shortcut Ctrl+Alt+V did.

sorry, last time I checked the browser api didn't let you access the html of the selection

> I would suggest to declutter web page before clipping.

If you know some "decluttering library" I could try to include it. :smile:

**Comment by pbek** [comment]
You could script the web scraper yourself now, see #16 and #17. :wink:
