### ISSUE TITLE
Feature Request: Add Bookmarks from Bookmark Menu

### ISSUE THREAD

**Issue by sunjam** [qownnotes/web-companion#8]
Suggestion:  I'd like to be able to add bookmarks already present in the bookmark menu, toolbar or folder on Firefox or Chrome to _Web Companion_.  Very nice app, just cannot find a way to do this.  Tested on Firefox.

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 19.5.2
- you now can **import all browser bookmarks**

There now is a new release, could you please test it and report if it works for you?

**Comment by sunjam** [comment]
It found the several hundred bookmarks and claimed to successfully import, but inside the new note it is empty besides:

`Note 2019-05-03T22.35.54`
`========================`

**Comment by pbek** [comment]
There should be a note named `Bookmarks`, don't you have that note?

**Comment by pjd79** [comment]
I have t(est this new feature in this new version and It works well for me.
It write all the bookmarks in the Bookmarks note.
It is a very useful addition.
Thank you for this wonderful work.

**Comment by pbek** [comment]
Great, thank you for testing! 😄
