### ISSUE TITLE
Is this extension compatible with Nextcloud Bookmarks ?

### ISSUE THREAD

**Issue by iSpeeX** [qownnotes/web-companion#9]
Hello,

I just find out about this companion app and I was wondering if it's compatible with Nextcloud Bookmarks ?
Just like Qownnotes + Nextcloud Notes.

Thanks
Best regards

**Comment by pbek** [comment]
You can import the bookmarks with QOwnNotes, see https://github.com/pbek/QOwnNotes/issues/1198

If that that answers your question feel free to close the issue.

**Comment by iSpeeX** [comment]
I meant with Nextcloud Bookmarks app, the import function only allows to gather links from notes to make it like bookmarks in the web companion. I just tried myself but that's not what I wanted

thank you anyway
best regards

**Comment by pbek** [comment]
so what do you want? showing the bookmarks of Nextcloud bookmarks? that's not in the scope of QOwnNotes, there are other browser extensions for that

**Comment by pbek** [comment]
> the import function only allows to gather links from notes

no, you can also import the bookmarks from Nextcloud bookmarks

**Comment by iSpeeX** [comment]
Well, the Qownnotes app only detect 10 bookmarks and it's links from my notes and notes my hundreds of Nextcloud Bookmarks, how can I do it ?

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by iSpeeX** [comment]
Today I use my own Nextcloud for Notes and Bookmarks (and more). Until today, I only used Qownnotes for my Nextcloud Notes (and it's working well).
Recently I heard about this web companion and I thought it would be great to have my NC bookmarks in my browser. 

Here it is for the story. After your answer I tried to import my bookmarks in Qownnotes software and it only detects 10 bookmarks (without any details during the detection) but I have hundreds of them on Nextcloud.

Of course, my Nextcloud account is connected on Qownnotes. 

Is it clear?

Best regards

**Comment by pbek** [comment]
> After your answer I tried to import my bookmarks in Qownnotes software and it only detects 10 bookmarks (without any details during the detection) but I have hundreds of them on Nextcloud.

Can you please report that on https://github.com/pbek/QOwnNotes/issues/1198
